package com.app.english.ui.theme

import androidx.compose.ui.graphics.Color

// Feedback colors per spec §5.3.
val ScoreGreen = Color(0xFF2E7D32)
val ScoreYellow = Color(0xFFF9A825)
val ScoreRed = Color(0xFFC62828)

// ---- Light palette ----
val Primary = Color(0xFF1E88E5)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFFBBDEFB)
val OnPrimaryContainer = Color(0xFF0A2E50)
val Secondary = Color(0xFF26A69A)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFB2DFDB)
val OnSecondaryContainer = Color(0xFF00251A)
val Tertiary = Color(0xFFF9A825)
val OnTertiary = Color(0xFF000000)
val TertiaryContainer = Color(0xFFFFECB3)
val OnTertiaryContainer = Color(0xFF402D00)
val Surface = Color(0xFFFDFBFF)
val OnSurface = Color(0xFF1A1C1E)
val SurfaceVariant = Color(0xFFE0E2EC)
val OnSurfaceVariant = Color(0xFF43474E)
val Background = Color(0xFFFDFBFF)
val OnBackground = Color(0xFF1A1C1E)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val OutlineLight = Color(0xFF74777F)
val OutlineVariantLight = Color(0xFFC4C6D0)

// ---- Dark palette ----
val PrimaryDark = Color(0xFF90CAF9)
val OnPrimaryDark = Color(0xFF003258)
val PrimaryContainerDark = Color(0xFF0D47A1)
val OnPrimaryContainerDark = Color(0xFFD0E4FF)
val SecondaryDark = Color(0xFF80CBC4)
val OnSecondaryDark = Color(0xFF003731)
val SecondaryContainerDark = Color(0xFF005048)
val OnSecondaryContainerDark = Color(0xFFB2DFDB)
val TertiaryDark = Color(0xFFFFD180)
val OnTertiaryDark = Color(0xFF402D00)
val TertiaryContainerDark = Color(0xFF5D4037)
val OnTertiaryContainerDark = Color(0xFFFFECB3)
val SurfaceDark = Color(0xFF1A1C1E)
val OnSurfaceDark = Color(0xFFE3E2E6)
val SurfaceVariantDark = Color(0xFF43474E)
val OnSurfaceVariantDark = Color(0xFFC4C6D0)
val BackgroundDark = Color(0xFF1A1C1E)
val OnBackgroundDark = Color(0xFFE3E2E6)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val OutlineDark = Color(0xFF8E9099)
val OutlineVariantDark = Color(0xFF43474E)
