"""init: users, lessons, history, tts_cache

Revision ID: d5ccd34b98e6
Revises:
Create Date: 2026-07-11 14:38:54.422402
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'd5ccd34b98e6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book', sa.String(length=16), nullable=False),
    sa.Column('lesson_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('role_count', sa.Integer(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_book'), 'lessons', ['book'], unique=False)
    op.create_index(op.f('ix_lessons_lesson_no'), 'lessons', ['lesson_no'], unique=False)
    op.create_table('tts_cache',
    sa.Column('cache_key', sa.String(length=128), nullable=False),
    sa.Column('audio_path', sa.String(length=512), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_device_id'), 'users', ['device_id'], unique=True)
    op.create_table('history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.String(length=64), nullable=False),
    sa.Column('audio_path', sa.String(length=512), nullable=False),
    sa.Column('score_total', sa.Float(), nullable=False),
    sa.Column('score_pronunciation', sa.Float(), nullable=False),
    sa.Column('score_fluency', sa.Float(), nullable=False),
    sa.Column('score_completeness', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_lesson_id'), 'history', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_history_user_id'), 'history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_user_id'), table_name='history')
    op.drop_index(op.f('ix_history_lesson_id'), table_name='history')
    op.drop_table('history')
    op.drop_index(op.f('ix_users_device_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tts_cache')
    op.drop_index(op.f('ix_lessons_lesson_no'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_book'), table_name='lessons')
    op.drop_table('lessons')
    # ### end Alembic commands ###
